apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-webapp-deployment
  namespace: my-name-space
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-webapp
  template:
    metadata:
      name: node-webapp
      labels:
        app: node-webapp
    spec:
      containers:
        - name: node-webapp
          image: olixc/node-webapp
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "100m"
              memory: "256Mi"
